# Generated by Django 4.1.5 on 2023-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0003_product_female'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email1', models.CharField(default='', max_length=100)),
                ('email2', models.CharField(default='', max_length=100)),
                ('instagram', models.CharField(default='', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('copyright', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
