# Generated by Django 4.1.5 on 2023-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('Creditcard', models.CharField(default='', max_length=20)),
                ('Exp', models.CharField(default='', max_length=5)),
                ('Cvc', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50)),
            ],
        ),
    ]
