# Generated by Django 4.1.5 on 2023-02-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0006_payment_sub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub',
            new_name='Subscribe',
        ),
    ]
