# Generated by Django 4.1.5 on 2023-02-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0009_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
    ]
