# Generated by Django 4.1.5 on 2023-02-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0010_remove_register_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='RegisterUser',
        ),
    ]
