# Generated by Django 4.1.5 on 2023-02-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0011_rename_register_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_ProductMale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaleApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Unique_ProductFemale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaleApp.product_female')),
            ],
        ),
    ]
