# Generated by Django 4.1.5 on 2023-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0013_unique_productfemale_image_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product_female',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
