# Generated by Django 4.1.5 on 2023-02-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0015_product_image_one_product_image_three_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='product_female',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='product_female',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='product_female',
            name='image_two',
        ),
    ]
