# Generated by Django 4.1.5 on 2023-02-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0016_remove_product_image_one_remove_product_image_three_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_M_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaleApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='P_F_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaleApp.product_female')),
            ],
        ),
    ]
