# Generated by Django 4.1.5 on 2023-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0017_p_m_images_p_f_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_female',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_female',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
