# Generated by Django 4.1.5 on 2023-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0019_remove_product_female_image_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number_click',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
