# Generated by Django 4.1.5 on 2023-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0020_category_number_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='adress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='birthday',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='surname',
            field=models.CharField(default='', max_length=12),
        ),
    ]
