# Generated by Django 4.1.5 on 2023-02-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaleApp', '0021_registeruser_adress_registeruser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
