# Generated by Django 4.1.5 on 2023-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0023_orders_male_orders_female'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_female',
            name='gift',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders_female',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orders_male',
            name='gift',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders_male',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
