# Generated by Django 4.1.5 on 2023-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaleApp', '0025_registeruser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='product_female',
            name='gender',
            field=models.CharField(default='Female', max_length=20),
        ),
    ]
